server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://120.78.182.26:3306/onlineStore?useSSL=false&characterEncoding=utf-8
        username: root
        password: swingLina@...
        driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.LinSY.backend.pojo  # 注意：对应实体类的路径

logging:
  level:
    com :
      LinSY:
        backend :
          mapper : debug




